### ISSUE TITLE
Superscript don't work with angular

### ISSUE THREAD

**Issue by alexis-puska** [ckeditor/ckeditor5-angular#132]
Hi all,

I have a problem with angular 7 and ckEditor 4 / 5. I have add this dependencies to my project 
```
    "@ckeditor/ckeditor5-angular": "^1.1.0",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.3",
    "@ckeditor/ckeditor5-build-classic": "^12.3.1",
```
This project was created with JHipster and user webpack

When a create a configuration file for CKEditor 

```Typescript
export const CkeditorConfig = {
  format_tags: 'p;h1;h2;h3;h4;h5;h6;pre',
  toolbar: ['bold', 'superscript']
};
```

Inside my component, import the configuration
```Typescript
import { CkeditorConfig } from '../../utils/ckeditorConfig';
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';

export class FaqUpdateComponent implements OnInit {
  public Editor = ClassicEditor;
  ckeditorConfig: any;

  //component stuff
}
```

Inside my template

```Html
 <ckeditor [editor]="Editor" [config]="ckeditorConfig" data="{{content.value}}" (change)="onChange($event)" required></ckeditor> 
```

I see the bold button for editor but no superscript, I get this error inside the console of the browser : 

toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable

When i read the documentation the superscript element is inside the basci style plugins package and inside the default build basic, i don't understand the missing step ?

Thank's

**Comment by Mgsy** [comment]
Hello, your solution doesn't work, because you import `ckeditor5-build-classic` which has predefined set of features and `superscript` isn't on that list, please see - https://github.com/ckeditor/ckeditor5-build-classic/blob/master/src/ckeditor.js. 

If you'd like to add this feature to the editor, you should create a custom build with `superscript` plugin. [Here](https://github.com/ckeditor/ckeditor5-build-classic/blob/master/src/ckeditor.js) you'll find a guide on how to do it. 

After creating a build, just import it to your component instead of `@ckeditor/ckeditor5-build-classic`.
