### ISSUE TITLE
How to ingrate CKEditor5 Mention in Angular

### ISSUE THREAD

**Issue by ImTung** [ckeditor/ckeditor5-angular#158]
Try to import via `<ckeditor [editor]="Editor"
    [config]="editorConfig">` but still don't know how to make it work.

Please suggest any ideas, thank you so much.

**Comment by Mgsy** [comment]
Hi! You should start by creating a custom build which will have mentions plugin included. [Here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) is the guide which explains how to do it. 

After that, you should integrate this build with your Angular application. Please, see our [Angular integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html) (note that you should import your custom build instead of our `ckeditor5-build-classic`).

**Comment by ImTung** [comment]
Thanks @Mgsy
