### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by Karman40** [ckeditor/ckeditor5-angular#178]
This likely means that the library (@ckeditor/ckeditor5-angular) which declares CKEditorModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

5 export declare class CKEditorModule {

![image](https://user-images.githubusercontent.com/32225709/76909585-dd512380-68ab-11ea-848f-dda4d6b11bcf.png)

    Angular: ^9.0.6
    "@ckeditor/ckeditor5-angular": "^1.2.2",

**Comment by ma2ciek** [comment]
Hm, the problem is that we want to support many Angular versions starting from version 5. And unfortunately changing the library builder might be not so easy for us as older versions won't compile correctly then. :disappointed:

**Comment by Karman40** [comment]
Thanks for the quick response!

Do you have a short temporary idea to fix the problem?

**Comment by pdentener** [comment]
I've been using CKEditor with Angular 9 without a problem since Angular 9 has been released. First with Ivy disabled, but then with Ivy enabled. Am using it now with `9.0.7`.

That doesn't help you, but maybe we can spot a difference? I'm simply importing the `CKEditorModule` via `import { CKEditorModule } from '@ckeditor/ckeditor5-angular'` in a Shared module. That's it.

**Comment by Karman40** [comment]
My problem also solved with the following:

- node_modules delete
- package-lock.json delete
- npm i

**Comment by ma2ciek** [comment]
I'm relieved that this problem was related with an incorrect Angular / npm update :smile:
