### ISSUE TITLE
Expose ckConfig interface

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5-angular#18]
We can provide ckconfig in `config` attribute.
Can You export it's complete interface in `@ckeditor/ckeditor5-angular` ?
It woulde be very nice to have full type support.

**Comment by pomek** [comment]
I guess the [EditorConfig interface](https://docs.ckeditor.com/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html) describes the configuration enough.

I can imagine that your idea has some sense but it will be hard to maintain. `EditorConfig` contains options for most of the CKEditor 5's plugins. 

If we create a new plugin, it will force release this repository because the new plugin may introduce the new option in the interface.

**Comment by piernik** [comment]
You're right. So maybe only present `keys` that has `any` as value?

**Comment by pomek** [comment]
cc: @ma2ciek

**Comment by ma2ciek** [comment]
This is a complicated thing. As I've described in https://github.com/ckeditor/ckeditor5/issues/504#issuecomment-408404900, each plugin should extend some base CKEditor5 interfaces and then our editor builds should concatenate these type declarations into one file, so they can be published with these declarations easily.

I've provided simple declarations in the https://github.com/ckeditor/ckeditor5-angular/blob/master/src/ckeditor/ckeditor.ts, but obviously, they're incomplete. You can look at https://github.com/ckeditor/ckeditor5-angular/blob/master/src/app/simple-usage/simple-usage.component.ts to see, how they're used. Those can be imported as `import { CKEditor5 } from '@ckeditor/ckeditor5-angular/ckeditor';` I'll try to change the path in the future, so the `import { CKEditor5 } from '@ckeditor/ckeditor5-angular';` will be also possible.

**Comment by ma2ciek** [comment]
I'm closing it since it's already solved (https://github.com/ckeditor/ckeditor5-angular/blob/master/src/ckeditor/ckeditor.ts#L15).
