### ISSUE TITLE
Inline Font Styles Are Not Working Inside Table 

### ISSUE THREAD

**Issue by smitbaranwal** [ckeditor/ckeditor5-angular#237]
HTML table font inline styles are getting overridden by some other font styles. One HTML table with some styles on the first row is added as data on CKEditor 5 Angular version.
[https://stackblitz.com/edit/haifahrul-angular-ckeditor5?file=src/app/app.component.ts](Stackblitz URL: https://stackblitz.com/edit/haifahrul-angular-ckeditor5?file=src/app/app.component.ts)

Same HTML is displayed in HTML viewer as:
![image](https://user-images.githubusercontent.com/15996942/103228423-d2f1a900-4956-11eb-9116-60d567e6310a.png)

**Comment by FilipTokarski** [comment]
Hi, I'm not sure if I get this right. First, the link you provided doesn't load the editor and throws an error. It works only after removing all `CKEditorInspector` imports. Now, when it loads it looks different than the image you attached - font has default styles in every row. I also copied the content to another editor to check it, and again it's using default font style ( I can't see it being overriden anywhere in inline styles ).
  
What do I miss? Could you please explain what is the problem here and provide detailed steps, so that we could reproduce this?
