### ISSUE TITLE
The editor lose focus when trying to edit a table

### ISSUE THREAD

**Issue by medmor** [ckeditor/ckeditor5-angular#239]
I want to show the editor just when the user need to edit text. And when the user clicks out (focusout), the editor is hidden.
But, when I try to edit a table, the editor lose focus.
Here is replication of the problem on stackblitz https://stackblitz.com/edit/ckeditor5-angular-focus-problem?file=src%2Fapp%2Fapp.component.ts

https://user-images.githubusercontent.com/35731087/104231049-ae192d80-544e-11eb-8bbf-5bd7d5fc8303.mp4

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. If I understood your use case correctly, I'm afraid this may not be achievable right out-of-the-box, because of [how the focus works](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/focus-tracking.html#focus-in-the-editor-engine). But to be sure, could you explain once again precisely what you want to achieve and decisions you made to do this?

**Comment by medmor** [comment]
Thank you FilipTokarski, now I understand better [how the focus works.](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/focus-tracking.html#focus-in-the-editor-engine)
The work around that I am using now is to check first `!event.relatedTarget` and then I hide the editor, and it s working well.

**Comment by FilipTokarski** [comment]
I'm glad I could help. I'll close this ticket then.
