### ISSUE TITLE
npm run build error ?

### ISSUE THREAD

**Issue by ManikandanTh** [ckeditor/ckeditor5-angular#261]
Hi,
I have installed webpack in project and ckeditor 5. while give npm run build it shows this error ?
![image](https://user-images.githubusercontent.com/79127262/120264967-971f8e80-c2bc-11eb-8422-467af08b0e9e.png)

**Comment by FilipTokarski** [comment]
Hi, at first look it seems that you don't have all needed packages ( ckeditor5-dev-utils in this case? ) installed. But in order to look into this, we'll need more information about your environment and a step-by-step description to reproduce this error.
  
Meanwhile, you can follow the docs on [integration with Angular](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html).
