### ISSUE TITLE
How to add a new button to the toolbar wich can fire 2 actions bold and centering the text

### ISSUE THREAD

**Issue by outemzabetsamy** [ckeditor/ckeditor5-angular#277]
How to add a new button to the toolbar wich can fire 2 actions bold and centering the text

**Comment by FilipTokarski** [comment]
Hi, here's the minimal code needed for this case:

```js
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';

class CustomPlugin extends Plugin {
    init() {
        const editor = this.editor;

        editor.ui.componentFactory.add( 'customPlugin', locale => {
            const view = new ButtonView( locale );

            view.set( {
                label: 'Custom button',
                withText: true,
                tooltip: true
            } );

            // Callback executed once the toolbar icon is clicked.
            view.on( 'execute', () => {
                editor.commands.execute( 'bold' );
                editor.commands.execute( 'alignment', { value: 'center' } );
            } );

            return view;
        } );
    }
}
```
This code creates a new plugin and registers a toolbar button. When the button is clicked, the specified commands are executed. Remember that in order to execute those commands, you need to have `alignment` and `bold` plugins installed as well.
Then you need to add this new `CustomPlugin` to the editor configuration and the toolbar, [like you would do with any other plugin](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-an-editor) and you're ready to go:


https://user-images.githubusercontent.com/34380544/134294106-73319b0d-8de2-4696-a88f-4b81a74ff780.mp4



 If you'd like to know more about how to create a plugin, please see the docs on [creating a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html).
  
Hope that helps!

**Comment by iKrishnaSahu** [comment]
@FilipTokarski I just started using ckeditor. Could you help me where exactly I have to mention `CustomPlugin` in my code so that it will appear in toolbar.

**Comment by ashishforgrz** [comment]
@FilipTokarski where do we need to add this code, I cannot directly use it in my editor as I have implemented CKEditor 5 on my VisualForce page, so do I need to add this in ckeditor.js inside src folder of ckeditor build. Or I do need to implement it another way. Or you can show me your configuration

**Comment by Witoso** [comment]
> so do I need to add this in ckeditor.js inside src folder of ckeditor build.

Yes, it can be a separate file, and this plugin later needs to be added to the config during the editor initialization.

**Comment by ashishforgrz** [comment]
By not changing anything in ckeditor4 build folder, I was able to add custom button on my toolbar without using any import through `editor.ui.addButton` but due to my project's limitations, I cannot do so with CKEditor 5. 
I am trying to add custom plugin button and functionality code directly from the file where I am implementing my ckeditor 5 which was possible for ckeditor 4 
`<apex:page controller="EditorController" showHeader="false" id="thepageid">


    <apex:includescript value="{!URLFOR($Resource.ckeditor, 'ckeditor5/build/ckeditor.js')}" />

    <apex:form id="theformid">
        <textarea id="editor1" styleClass="ckeditor" richtext="false" />
    </apex:form>

    <script type="text/javascript">
        var lexOrigin = '{!JSENCODE(lexOrigin)}';
        let editor;
        window.onload = function () {
            var fieldname = '{!JSENCODE($CurrentPage.parameters.fieldname)}';
            var instanceId = '{!JSENCODE($CurrentPage.parameters.instanceId)}';
            var editValue = '';
            var editorId = '#editor1';
            editor = ClassicEditor.create(document.querySelector(editorId), {
                
                toolbar: ['customPlugin', 'Bold', 'Italic'],
            }).then(createdEditor => {
                editor = createdEditor;
                editor.ui.componentFactory.add('customButton', locale => {
                    const view = new editor.ButtonView(locale);
                    view.set({
                        label: 'Custom Button',
                        icon: 'https://csod072009s.searchunify.com/resources/Assets/upload-image.svg',
                        tooltip: true
                    });
                    view.on('execute', () => {
                        editor.execute('customCommand');
                    });

                    return view;
                });

            })
        }
    </script>
</apex:page>`
Please let me know what could be done as i only want to add custom plugin from this file with the same structure. Also the above code is not giving any custom plugin.

**Comment by Witoso** [comment]
@ashishforgrz using the CKEditor4 plugin's code will not work in the CKEditor 5. [The UI library ](https://ckeditor.com/docs/ckeditor5/latest/framework/architecture/ui-library.html) is different and requires object initialization from the UI library. 

```javascript
const view = new editor.ButtonView(locale);
```

This is an incorrect way in CKE5. Read more about [components](https://ckeditor.com/docs/ckeditor5/latest/framework/architecture/ui-components.html) and [plugins](https://ckeditor.com/docs/ckeditor5/latest/framework/plugins/creating-simple-plugin-timestamp.html).

**Comment by ashishforgrz** [comment]
@Witoso my only problem is that i was able to add any button into ckeditor 4 toolbar with `editor.ui.addButton ` but not able to use the same process with CKEditor supported components `editor.ui.componentFactory.add `.
Can you please let me know what am i doing wrong in the above code. I haven't got any solution from the documentation as i mentioned.

**Comment by Witoso** [comment]
As I mentioned, it's not possible to use the same process in CKE5 as you used in CKE4. To create a button, you need to import from the `ui` package, for example:

```javascript
import { ButtonView } from '@ckeditor/ckeditor5-ui';

const actionButton = new ButtonView();

actionButton.set( {
    label: 'Action button',
    withText: true,
    class: 'ck-button-action'
} );
```

**Comment by ashishforgrz** [comment]
I am stuck with my flow, I cannot import ButtonView for my build as I am directly importing ckeditor/build.ckeditor.js file and directly using ClassicEditor in my VF page where import doesn't work.  Everything's working fine but I am not able to add custom button by any way. Please let me know if there's any way to get out of it. @Witoso

**Comment by Witoso** [comment]
Extending predefined builds and adding buttons to them will not work in CKEditor 5, [you need to create your build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html) or [use the DLL method](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds.html).
