### ISSUE TITLE
Image layout is broken with CKFinder upload.

### ISSUE THREAD

**Issue by thruthesky** [ckeditor/ckeditor5-angular#38]
Hello there. Thank you for CKEditor5-Angular.

I applied CKFInder and it works. But I have a situation.

I uploaded image on `post page` like below. `post page` is being lazy loaded and `post page` is the only page bundled with CKEditor5-Angular.
![image](https://user-images.githubusercontent.com/5080329/45916743-97c1bf00-be9d-11e8-9648-fb07dac8d788.png)

I saved the content into database and it displays on `view page` like below.
![image](https://user-images.githubusercontent.com/5080329/45916747-a1e3bd80-be9d-11e8-8a08-9821723cd231.png)

I guess the Styles are not loaded on `view page` ( which is also being lazy loaded ).

I temporarily added styles like below.

````
.image-style-side {
  max-width: 50%
}

.image-style-side {
  float: right;
  margin-left: var(--ck-image-style-spacing)
}
````
Is there a right way to do it?

Thank you.

**Comment by ma2ciek** [comment]
Hi, @thruthesky.

The problem has nothing to do with the CKFinder. It happens, because we don't bundle inline styles (sometimes we do, but not in this scenario) into the content that comes from `editor.getData()` and we don't have any mechanism to get styles from the editor yet. So the responsibility to style the editor content and the output content lands on the developer.

The question of how to style the output content [was already raised on the SO]( https://stackoverflow.com/questions/52401319/apply-styles-to-html-output-of-ckeditor-5) and the topic is described [here](https://github.com/ckeditor/ckeditor5/issues/773).

For the image feature the way you style it is fine IMO.

**Comment by yogeshbansal** [comment]
@thruthesky : Could you please share the code how you are using Ckfinder and inserting image and storing into the database. I am having a hard time in this.

**Comment by yadavsunilmoravia** [comment]
Please let me know details since I am also having same issue.

**Comment by ma2ciek** [comment]
The documentation for the CKFinder is available here - [https://ckeditor.com/docs/ckfinder/ckfinder3](https://ckeditor.com/docs/ckfinder/ckfinder3) - with guides for different backend languages.

**Comment by id1945** [comment]
I find it better to use this one.
https://stackblitz.com/edit/ngx-summernote
