### ISSUE TITLE
SEO - repository can't be found in google search

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-angular#45]
I've been trying `ckeditor 5 angular 2` and some variations, nothing shows up.

Fortunately, the first 3 results link later to this package

<img width="673" alt="screen shot 2018-10-11 at 16 26 22" src="https://user-images.githubusercontent.com/2768047/46811194-8d933200-cd72-11e8-9f8e-937cb50f979a.png">

**Comment by Reinmar** [comment]
I think the main page where we'd like people to land is actually the 3rd link there. It will slowly move up – we just published it. We'll have links to it from other places soon. It's actually not that bad that this repo isn't high because most people would need to click the link to documentation that we have in the readme anyway.

**Comment by Reinmar** [comment]
IDK why this repo is omitted in the results, but the docs are first, so it's perfect:

![image](https://user-images.githubusercontent.com/156149/48059768-5faadd00-e1ba-11e8-87b1-7ade2deab347.png)
