### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by piecioshka** [ckeditor/ckeditor5-angular#5]
Hi CKEditor team!

Proper way to set description is do not use Angular version, so instead of:
`Official CKEditor 5 Angular 2+ component. `
you should use:
`Official CKEditor 5 Angular component. `

Regards!

**Comment by Reinmar** [comment]
Hi @piecioshka!

Thanks for pointing this out. I know that there are AngularJS (for 1.x) and Angular (for 2+) so that "2+" is superfluous, but is it really that bad to use "Angular 2+"? I can see many people doing the same:

![image](https://user-images.githubusercontent.com/156149/40967778-4467dfd6-68b4-11e8-8e53-597a2b12e231.png)

It's a description of a repo and its job is to clarify what this repo is about. If adding 2+ makes it clearer, I'd rather go this way.
